/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as scopePaymentSol from "./ScopePayment.sol";
export * as scopeTokenSol from "./ScopeToken.sol";
export * as scopeVestingSol from "./ScopeVesting.sol";
export * as interfaces from "./interfaces";
export * as presets from "./presets";
export * as v2 from "./v2";
