/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBlockscopeVestingSol from "./IBlockscopeVesting.sol";
export type { iBlockscopeVestingSol };
export type { IOwnablePausable } from "./IOwnablePausable";
