/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlockScopePayment } from "./IBlockScopePayment";
export type { IBlockScopeVesting } from "./IBlockScopeVesting";
export type { IOwnablePausable } from "./IOwnablePausable";
