/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scopePaymentSol from "./ScopePayment.sol";
export type { scopePaymentSol };
import type * as scopeTokenSol from "./ScopeToken.sol";
export type { scopeTokenSol };
import type * as scopeVestingSol from "./ScopeVesting.sol";
export type { scopeVestingSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as presets from "./presets";
export type { presets };
import type * as v2 from "./v2";
export type { v2 };
