/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iBlockscopeVestingSol from "./IBlockscopeVesting.sol";
export { IOwnablePausable__factory } from "./IOwnablePausable__factory";
